### ISSUE TITLE
Unexpected https error

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-upload-validate#39]
```
not ok 50 tm2z.parsecolor: expected error message
  ---
    operator: equal
    expected:
      'Invalid style\n'
    actual:
      '_http_client.js:75\n    throw new Error(\'Protocol "\' + protocol + \'" not supported. \' +\n          ^\nError: Protocol "https:" not supported. Expected "http:".\n    at new ClientRequest (_http_client.js:75:11)\n    at Object.exports.request (http.js:49:10)\n    at Object.exports.request (https.js:136:15)\n    at Get.request (/Users/tmcw/src/mapbox-upload-validate/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:92:22)\n    at Get.perform (/Users/tmcw/src/mapbox-upload-validate/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:132:30)\n    at Get.asBuffer (/Users/tmcw/src/mapbox-upload-validate/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:286:10)\n    at TileJSON.get (/Users/tmcw/src/mapbox-upload-validate/node_modules/tilejson/lib/tilejson.js:207:19)\n    at /Users/tmcw/src/mapbox-upload-validate/node_modules/tilejson/lib/tilejson.js:60:22\n    at /Users/tmcw/src/mapbox-upload-validate/node_modules/tilejson/lib/tilejson.js:237:13\n    at new TileJSON (/Users/tmcw/src/mapbox-upload-validate/node_modules/tilejson/lib/tilejson.js:58:16)\n'
  ...
```

Getting this error on a clean checkout of master. Not sure if this is a configuration difference or a node 0.12 difference.

**Comment by jlyon** [comment]
Also getting this with node 0.12.

**Comment by springmeyer** [comment]
Not seeing this currently with node v0.12. Going to close therefore - feel free to re-open if it pops up again.
